import argparse
import json
from pathlib import Path

from live_db_common import DEFAULT_DB_RETRY_ATTEMPTS, close_pg_quietly, connect_pg, is_retryable_pg_error, sleep_before_retry
from selectdb_common import ensure_selectdb_schema, insert_model_run, load_json_file
from training_common import write_json


def parse_args():
    parser = argparse.ArgumentParser(description="Bulk load a selected top-K URL TSV into selectdb.")
    parser.add_argument("--select-db-url", required=True, help="Target selectdb URL.")
    parser.add_argument("--selection-tsv", type=Path, required=True, help="TSV generated by score_live_crawler.py.")
    parser.add_argument("--run-label", required=True, help="Logical run label stored in selectdb.")
    parser.add_argument("--cutoff-datetime", default="", help="Optional training split cutoff stored with the run.")
    parser.add_argument("--model-path", default="", help="Model path stored with the run metadata.")
    parser.add_argument("--train-metrics-path", type=Path, default=None, help="Training metrics JSON path.")
    parser.add_argument("--eval-metrics-path", type=Path, default=None, help="Eval metrics JSON path.")
    parser.add_argument("--selection-metrics-path", type=Path, default=None, help="Selection summary JSON path.")
    parser.add_argument("--source-summary-path", type=Path, default=None, help="Source export summary JSON path.")
    parser.add_argument("--summary-path", type=Path, required=True, help="Output JSON summary path.")
    parser.add_argument(
        "--db-retry-attempts",
        type=int,
        default=DEFAULT_DB_RETRY_ATTEMPTS,
        help="Retry attempts when the selectdb connection drops during schema creation or COPY load.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if not args.selection_tsv.is_file():
        raise FileNotFoundError(args.selection_tsv)
    if args.db_retry_attempts <= 0:
        raise ValueError("--db-retry-attempts must be > 0")

    ensure_selectdb_schema(args.select_db_url, db_retry_attempts=args.db_retry_attempts)
    train_metrics = load_json_file(args.train_metrics_path)
    eval_metrics = load_json_file(args.eval_metrics_path)
    selection_metrics = load_json_file(args.selection_metrics_path)
    source_paths = load_json_file(args.source_summary_path)

    inserted_rows = 0
    for attempt in range(1, args.db_retry_attempts + 1):
        conn = None
        try:
            conn = connect_pg(
                args.select_db_url,
                readonly=False,
                application_name="indexselection_v1_selectdb_load",
            )
            run_id = insert_model_run(
                conn,
                run_label=args.run_label,
                cutoff_datetime=args.cutoff_datetime or None,
                model_path=args.model_path,
                train_metrics=train_metrics,
                eval_metrics=eval_metrics,
                selection_metrics=selection_metrics,
                source_paths=source_paths,
            )

            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TEMP TABLE selected_urls_stage (
                        url TEXT NOT NULL,
                        score DOUBLE PRECISION NOT NULL,
                        first_seen TIMESTAMPTZ
                    ) ON COMMIT DROP
                    """
                )
                with args.selection_tsv.open("r", encoding="utf-8") as f:
                    cur.copy_expert(
                        """
                        COPY selected_urls_stage (url, score, first_seen)
                        FROM STDIN
                        WITH (FORMAT csv, DELIMITER E'\\t', HEADER true)
                        """,
                        f,
                    )

                cur.execute("TRUNCATE TABLE public.selected_urls_current")
                cur.execute(
                    """
                    INSERT INTO public.selected_urls_current (url, score, first_seen, run_id)
                    SELECT DISTINCT ON (url)
                        url,
                        score,
                        first_seen,
                        %s
                    FROM selected_urls_stage
                    ORDER BY url, score DESC
                    """,
                    (run_id,),
                )
                inserted_rows = cur.rowcount
                cur.execute("ANALYZE public.selected_urls_current")
            conn.commit()
            break
        except Exception as exc:
            if conn is not None:
                conn.rollback()
            if not is_retryable_pg_error(exc) or attempt >= args.db_retry_attempts:
                raise
            print(f"[selectdb_load] retry attempt={attempt + 1} error={exc}", flush=True)
            sleep_before_retry(attempt)
        finally:
            close_pg_quietly(conn)

    summary = {
        "run_label": args.run_label,
        "selection_tsv": str(args.selection_tsv),
        "inserted_rows": int(inserted_rows),
        "cutoff_datetime": args.cutoff_datetime or None,
        "model_path": args.model_path,
        "train_metrics_path": str(args.train_metrics_path) if args.train_metrics_path else None,
        "eval_metrics_path": str(args.eval_metrics_path) if args.eval_metrics_path else None,
        "selection_metrics_path": str(args.selection_metrics_path) if args.selection_metrics_path else None,
        "source_summary_path": str(args.source_summary_path) if args.source_summary_path else None,
        "db_retry_attempts": int(args.db_retry_attempts),
    }
    write_json(args.summary_path, summary)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
